apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-app-ingress
spec:
  rules:
  - host: authapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authwebapp
            port:
              number: 80