apiVersion: v1
kind: Secret
metadata:
  name: auth-app-secret
type: Opaque
data:
  # Base64 encoded values
  Jwt__SecretKey: WW91clN1cGVyU2VjcmV0S2V5SGVyZTEyMzQ1Njc4OTAxMjM0NTY3ODkw  # YourSuperSecretKeyHere12345678901234567890
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password